global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Text;
global using System.Xml.Serialization;
global using AsmResolver.DotNet;
global using AsmResolver.DotNet.Signatures;
global using BitMono.API.Configuration;
global using BitMono.Core.Extensions;
global using BitMono.Core.Protecting.Analyzing;
global using BitMono.Core.Protecting.Injection;
global using BitMono.Core.Protecting.Resolvers;
global using BitMono.Core.TestCases.CustomAttributes;
global using BitMono.Shared.Models;
global using FluentAssertions;
global using Microsoft.Extensions.Configuration;
global using Newtonsoft.Json;
global using Xunit;
global using BitMono.Core.Tests.Shared;
global using BitMono.Protections;
global using CustomAttributeNamedArgument = AsmResolver.DotNet.Signatures.CustomAttributeNamedArgument;
global using MethodAttributes = AsmResolver.PE.DotNet.Metadata.Tables.Rows.MethodAttributes;
global using TypeAttributes = AsmResolver.PE.DotNet.Metadata.Tables.Rows.TypeAttributes;