namespace BitMono.Core.Analyzing.Baml;

/// <summary>WPF BAML record type identifiers (the first byte of each record).</summary>
internal enum BamlRecordType : byte
{
    ClrEvent = 0x13,
    Comment = 0x17,
    AssemblyInfo = 0x1c,
    AttributeInfo = 0x1f,
    ConstructorParametersStart = 0x2a,
    ConstructorParametersEnd = 0x2b,
    ConstructorParameterType = 0x2c,
    ConnectionId = 0x2d,
    ContentProperty = 0x2e,
    DefAttribute = 0x19,
    DefAttributeKeyString = 0x26,
    DefAttributeKeyType = 0x27,
    DeferableContentStart = 0x25,
    DefTag = 0x18,
    DocumentEnd = 0x2,
    DocumentStart = 0x1,
    ElementEnd = 0x4,
    ElementStart = 0x3,
    EndAttributes = 0x1a,
    KeyElementEnd = 0x29,
    KeyElementStart = 0x28,
    LastRecordType = 0x39,
    LineNumberAndPosition = 0x35,
    LinePosition = 0x36,
    LiteralContent = 0xf,
    NamedElementStart = 0x2f,
    OptimizedStaticResource = 0x37,
    PIMapping = 0x1b,
    PresentationOptionsAttribute = 0x34,
    ProcessingInstruction = 0x16,
    Property = 0x5,
    PropertyArrayEnd = 0xa,
    PropertyArrayStart = 0x9,
    PropertyComplexEnd = 0x8,
    PropertyComplexStart = 0x7,
    PropertyCustom = 0x6,
    PropertyDictionaryEnd = 0xe,
    PropertyDictionaryStart = 0xd,
    PropertyListEnd = 0xc,
    PropertyListStart = 0xb,
    PropertyStringReference = 0x21,
    PropertyTypeReference = 0x22,
    PropertyWithConverter = 0x24,
    PropertyWithExtension = 0x23,
    PropertyWithStaticResourceId = 0x38,
    RoutedEvent = 0x12,
    StaticResourceEnd = 0x31,
    StaticResourceId = 0x32,
    StaticResourceStart = 0x30,
    StringInfo = 0x20,
    Text = 0x10,
    TextWithConverter = 0x11,
    TextWithId = 0x33,
    TypeInfo = 0x1d,
    TypeSerializerInfo = 0x1e,
    XmlAttribute = 0x15,
    XmlnsProperty = 0x14,
}
