global using AsmResolver.DotNet;
global using AsmResolver.DotNet.Builder;
global using AsmResolver.DotNet.Serialized;
global using AsmResolver.PE.File.Headers;
global using Autofac.Extensions.DependencyInjection;
global using BitMono.API.Protecting.Contexts;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using NullGuard;
global using System;
global using System.Collections.Generic;
global using System.Threading;
global using System.Threading.Tasks;
global using IAssemblyResolver = AsmResolver.DotNet.IAssemblyResolver;
global using IModule = Autofac.Core.IModule;