global using BitMono.API.Protecting;
global using BitMono.API.Protecting.Contexts;
global using BitMono.API.Protecting.Injection;
global using BitMono.API.Protecting.Injection.FieldDefs;
global using BitMono.API.Protecting.Injection.MethodDefs;
global using BitMono.API.Protecting.Pipeline;
global using BitMono.API.Protecting.Renaming;
global using BitMono.Core.Protecting.Analyzing.DnlibDefs;
global using BitMono.Core.Protecting.Analyzing.TypeDefs;
global using BitMono.Core.Protecting.Attributes;
global using BitMono.Core.Protecting.Helpers;
global using BitMono.Runtime;
global using BitMono.Utilities.Extensions.dnlib;
global using dnlib.DotNet;
global using dnlib.DotNet.Emit;
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Threading;
global using System.Threading.Tasks;
global using MethodAttributes = dnlib.DotNet.MethodAttributes;
global using ILogger = Serilog.ILogger;