global using System.Collections.Generic;
global using System.Diagnostics.CodeAnalysis;
global using System.IO;
global using System.Linq;
global using System.Threading;
global using Autofac;
global using BitMono.Core.Extensions;
global using BitMono.Host;
global using BitMono.Host.Extensions;
global using BitMono.Host.Modules;
global using BitMono.Obfuscation;
global using BitMono.Shared.Models;
global using Microsoft.Build.Framework;
global using Microsoft.Build.Utilities;
global using Microsoft.Extensions.Options;
global using Serilog;
global using ILogger = Serilog.ILogger;