global using Autofac;
global using Autofac.Extensions.DependencyInjection;
global using BitMono.API.Configuration;
global using BitMono.API.Protecting;
global using BitMono.GUI.API;
global using BitMono.GUI.Data;
global using BitMono.GUI.Shared.Alerting;
global using BitMono.GUI.Shared.Inputs;
global using BitMono.Host.Modules;
global using BitMono.Obfuscation;
global using BitMono.Shared.Models;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Forms;
global using Microsoft.JSInterop;
global using Serilog;
global using Serilog.Core;
global using Serilog.Events;
global using Serilog.Formatting;
global using Serilog.Formatting.Display;
global using System.Collections.Concurrent;
global using System.Reflection;
global using BitMono.GUI.Utilities.Extensions;
global using static BitMono.Utilities.Extensions.Collections.CollectionExtensions;
global using ILogger = Serilog.ILogger;