name: BitMono.Core

on:
  create:
    tags:
      - "*"
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/BitMono.Core.yaml'
      - '.github/actions/project-build/**'
      - 'src/BitMono.Core/**'
      - 'src/props/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/BitMono.Core.yaml'
      - '.github/actions/project-build/**'
      - 'src/BitMono.Core/**'
      - 'src/props/**'

jobs:
  build:
    name: "BitMono.Core Build"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write   # OIDC for NuGet Trusted Publishing

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v5
      name: Setup .NET
      with:
        dotnet-version: 9.x
        
    - uses: ./.github/actions/project-build
      id: project-build
      with:
        project_path: src/BitMono.Core
        github_token: ${{ secrets.GITHUB_TOKEN }}
        nuget_user: ${{ secrets.NUGET_USER }}
        nuget_push: true
        